services:
  mongo:
    image: mongo:7
    container_name: club-social-semana-06-mongo
    ports:
      - "27017:27017"
    volumes:
      - club-social-s06-data:/data/db
volumes:
  club-social-s06-data:
